### ISSUE TITLE
Retriever: Fails to handle 404 on app data requests

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray-archiver#134]
```
<7>Requsting App Data for: messengerlite.facebooklite.facebook
(node:10436) UnhandledPromiseRejectionWarning: Error: App not found (404)
    at /home/hapax/github/sociam/xray-archiver/pipeline/node_modules/google-play-scraper/lib/utils/request.js:42:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by AdamSlack** [comment]
fixed in #135
